const PORT = Number(process.env.PORT);
const SALT_ROUNDS = Number(process.env.SALT_ROUNDS);
const JWT_SECRET_KEY=String(process.env.JWT_SECRET_KEY)
const ACESS_TOKEN_EXPIRATION_TIME = String(process.env.ACESS_TOKEN_EXPIRATION_TIME)
const REFRESH_TOKEN_EXPIRATION_TIME = String(process.env.REFRESH_TOKEN_EXPIRATION_TIME)

export {
  PORT,
  SALT_ROUNDS,
  JWT_SECRET_KEY,
  ACESS_TOKEN_EXPIRATION_TIME,
  REFRESH_TOKEN_EXPIRATION_TIME,
}
